export enum ErrorCode {
    SERVICE_FAILED = "SERVICE_FAILED",
    FIELD_NOT_VALID = "FIELD_NOT_VALID",
    EMPTY_FIELD = "EMPTY_FIELD",
    ALREADY_EXISTS = "ALREADY_EXISTS",
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",
    NOT_VERIFIED = "NOT_VERIFIED",
    METHOD_NOT_IMPLEMENTED = "METHOD_NOT_IMPLEMENTED",
}