export enum RegistrationStep {
    PHONE_REGISTERED = "PHONE_REGISTERED",
    PHONE_VERIFIED = "PHONE_VERIFIED",
    USER_DETAILS_RECEIVED = "USER_DETAILS_RECEIVED",
    USER_VERIFIED = "USER_VERIFIED",
}
